### ISSUE TITLE
Unexpected errors when comparing a model

### ISSUE THREAD

**Issue by eposse** [ZeligsoftDev/CX4CBDDS#131]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

When comparing an AXCIOMA model with Papyrus Compare, many "Unexpected error" entries appear in the Error Log.

Although the user may continue to do the comparison, it is not clear if they are harmless or not.

#### Steps to reproduce

(This assumes that you have the CX4CBDDS git repository added in the git perspective and the 'papyrus' branch checked-out).

1. Import the BasicPubSub_new project from the CX4CBDDS git repo 'examples' folder into the workspace
1. Open the BasicPubSub_new model (BasicPubSub/ModelFiles/BasicPubSubPapyrus)
1. Open the assembly diagram (In the Model Explorer navigate to /BasicPubSub/assemblies/BasicPubSub_asm/BasicPubSub_asm and double click on the "NewCompositeStructureDiagram" item to open it)
1. Make some changes to the diagram, like moving a part.
1. Save the model.
1. Open the Git perspective (Window > Perspective > Open Perspective > Other... > Git)
1. Go to the "Git Staging" view.
1. Stage the /BasicPubSub/ModelFiles/BasicPubSubPapyrus.notation file (and the BasicPubSub/ModelFiles/BasicPubSubPapyrus.uml file if it appears). You may need to click the "Refresh" button in the top-right of the "Git Staging" view.
1. Go back to the Papyrus perspective (Window > Perspective > Open Perspective > Other... > Papyrus)
1. Open the Error Log view (Window > Show View > Error Log)
1. Delete the current log entries (right-click on the "Delete Log" button, a red [X] on the top-right of the Error Log view).
1. Right click on /BasicPubSub/ModelFiles/BasicPubSubPapyrus and select "Compare With > Index)
1. If prompted to switch to the Synchronization perspective, click on [Yes] (and optionally check the "Remember my decision" checkbox)
1. In the Synchronization view on the left, unfold BasicPubSub/ModelFiles, right-click on BasicPubSubPapyrus.notation and select "Open in Compare Editor"

#### Expected result

The Compare Editor opens and shows the Model differences, and no errors are logged.

#### Actual result

The Compare Editor opens and shows the Model differences, and many errors are logged. See the attached log file.

[exceptions.log](https://github.com/ZeligsoftDev/CX4CBDDS/files/4623762/exceptions.log)

**Comment by eposse** [comment]
The main exception is this: 

```
org.eclipse.papyrus.infra.core.resource.NotFoundException: No root defined in the model
	at org.eclipse.papyrus.uml.tools.model.UmlModel.lookupRoot(UmlModel.java:114)
	at org.eclipse.papyrus.uml.tools.service.ProfileDefinitionService.addRootProfileDecorationIfRequired(ProfileDefinitionService.java:140)
	at org.eclipse.papyrus.uml.tools.service.ProfileDefinitionService.startService(ProfileDefinitionService.java:121)
	at org.eclipse.papyrus.infra.core.services.internal.ServiceEntry.startService(ServiceEntry.java:154)
	at org.eclipse.papyrus.infra.core.services.internal.StartStartupEntry.startService(StartStartupEntry.java:83)
	at org.eclipse.papyrus.infra.core.services.ServicesRegistry.startServices(ServicesRegistry.java:1022)
	at org.eclipse.papyrus.infra.core.services.ServicesRegistry.startRegistry(ServicesRegistry.java:490)
	at org.eclipse.papyrus.compare.diagram.ide.ui.internal.ServicesRegistryInitializingHook.preLoadingHook(ServicesRegistryInitializingHook.java:37)
	at org.eclipse.emf.compare.ide.internal.utils.NotLoadingResourceSet.load(NotLoadingResourceSet.java:390)
	at org.eclipse.emf.compare.ide.internal.utils.NotLoadingResourceSet.create(NotLoadingResourceSet.java:155)
	at org.eclipse.emf.compare.ide.ui.internal.logical.ComparisonScopeBuilder.createScope(ComparisonScopeBuilder.java:519)
	at org.eclipse.emf.compare.ide.ui.internal.logical.ComparisonScopeBuilder.createMinimizedScope(ComparisonScopeBuilder.java:487)
	at org.eclipse.emf.compare.ide.ui.internal.logical.ComparisonScopeBuilder.build(ComparisonScopeBuilder.java:182)
	at org.eclipse.emf.compare.ide.ui.internal.logical.ComparisonScopeBuilder.create(ComparisonScopeBuilder.java:271)
	at org.eclipse.emf.compare.ide.ui.internal.structuremergeviewer.EMFCompareStructureMergeViewer.compareInputChanged(EMFCompareStructureMergeViewer.java:1518)
	at org.eclipse.emf.compare.ide.ui.internal.structuremergeviewer.EMFCompareStructureMergeViewer$CompareInputChangedJob.run(EMFCompareStructureMergeViewer.java:223)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

This occurs when opening a comparison, and as can be seen in the trace, when running a job of the EMFCompareStructureMergeViewer.

The exception originates in this piece of code:

```java
	public EObject lookupRoot() throws NotFoundException {
		if (resource == null || resource.getContents().isEmpty()) {
			// The root doesn't exist.
			throw new NotFoundException("No root defined in the model");
		}

		return resource.getContents().get(0);
	}
```

which is in class `org.eclipse.papyrus.uml.tools.model.UmlModel`. The particular instance is of type `org.eclipse.papyrus.uml.tools.model.ExtendedUmlModel`, which is loaded by Papyrus into its "modelSet", along with several other models, all of which have `resource` set to `null`, resulting in the above function throwing the `NotFoundException`.

**Comment by eposse** [comment]
The `lookupRoot` function throwing the exception is arrived at from `org.eclipse.papyrus.uml.tools.service.ProfileDefinitionService.startService()`, which starts by obtaining the `ExtendedUmlModel`, but since its `resource` is `null`, the code guarrantees that the execution path ends in the `throw` statement of the `lookupRoot` function. 

This strongly suggests that it is a bug in Papyrus itself.

**Comment by eposse** [comment]
A more detailed account of this error:



The error occurs when a comparison starts and the `EMFCompareStructureMergeViewer` creates a "comparison scope" which creates a `NotLoadingResourceSet` containing the Papyrus model files (.notation and .uml) to be compared. When creating this resource set, it loads these files but just before loading them it obtaind matching "pre-load hooks", which in this case includes the hook provided by Papyrus Compare: `org.eclipse.papyrus.compare.diagram.ide.ui.internal.ServicesRegistryInitializingHook`. 

This hook creates a Papyrus `ExtensionServicesRegistry`, and then starts it. When starting the ServiceRegistry, a service entry for `org.eclipse.emf.transaction.TransactionalEditingDomain` is initialized (`initService`) which tries to get an instance of the `ModelSet` serivice, which creates an instance of the model service, specifically an `org.eclipse.papyrus.infra.services.resourceloading.OnDemandLoadingModelSet`. This results in a call to `org.eclipse.papyrus.infra.core.resource.ModelsReader.readModel(ModelSet)` which reads models declared via an extension point: `org.eclipse.papyrus.infra.core.model`.

The models read are actually instantiated when processing the extension. The extension provides a class name which is loaded by the current class loader (presumably the one that loaded the Papyrus infra.core). Then this class is instantiated, and the new instances (such as an instance of `org.eclipse.papyrus.uml.tools.model.ExtendedUmlModel` which is a subclass of class `org.eclipse.papyrus.infra.core.resource.uml.UmlModel`) have their `resource` set to `null`, which eventually causes the exception.

After all these models are loaded, starting the service registry resumes by starting the services that have been added. In particular the problem occurs when starting the service `org.eclipse.papyrus.uml.tools.service.ProfileDefinitionService`. This looks for the model with id `org.eclipse.papyrus.infra.core.resource.uml.UmlModel`, which is the instance of `org.eclipse.papyrus.uml.tools.model.ExtendedUmlModel` loaded with via the `org.eclipse.papyrus.infra.core.model` extension point. As this instance has its resource  attribute set to `null` it goes on to call `org.eclipse.papyrus.uml.tools.service.ProfileDefinitionService.addRootProfileDecorationIfRequired(UmlModel)` passing this model as argument. This calls `org.eclipse.papyrus.uml.tools.model.UmlModel.lookupRoot()` which throws a `NotFoundException` when the resource is null.

It looks like the code for `org.eclipse.papyrus.uml.tools.service.ProfileDefinitionService.startService()`  is incorrect as it necessarily leads to the exception:

```java
	public void startService() throws ServiceException {
		final UmlModel umlModel = (UmlModel) modelSet.getModel(ExtendedUmlModel.MODEL_ID);
		try {
			if (null != umlModel.getResource() && umlModel.getResource().getContents().isEmpty()) {
				// ... 
			} else {
				addRootProfileDecorationIfRequired(umlModel);
			}
		} catch (NotFoundException e) {
			Activator.log.error(e);
		} catch (ServiceException e) {
			Activator.log.error(e);
		}
	}
```

The first line obtains the model with `resource` set to `null`, as the model was instantiated from the extension point without initializing its attributes. Hence execution necessarily goes to the "else" clause and calls `addRootProfileDecorationIfRequired`:

```java
	private final void addRootProfileDecorationIfRequired(final UmlModel umlModel) throws NotFoundException, ServiceException {
		final EObject rootElement = umlModel.lookupRoot();
		// ...
	}
```

... which starts by calling `lookupRoot`:

```java
	public EObject lookupRoot() throws NotFoundException {
		if (resource == null || resource.getContents().isEmpty()) {
			// The root doesn't exist.
			throw new NotFoundException("No root defined in the model");
		}
		return resource.getContents().get(0);
	}
```

... so the exception is necessarily thrown for models loaded via the extension point.

This means that this is a Papyrus bug, unless this code (the `ProfileDefinitionService`) was not designed to consider the case of models being loaded and instantiated dynamically via the `org.eclipse.papyrus.infra.core.model` extension point.
