### ISSUE TITLE
Newly created assembly part in a composite diagram cannot be resized

### ISSUE THREAD

**Issue by ysroh** [ZeligsoftDev/CX4CBDDS#177]
# **Issue and tracking information**

If you create a new part in a composite diagram it cannot be resized throwing the following exceptions.
It looks like this is a regression due to recent changes.

java.lang.NullPointerException
	at org.eclipse.papyrus.uml.diagram.composite.custom.utils.CompositeStructureDiagramUtils.getPartTypeFirstView(CompositeStructureDiagramUtils.java:108)
	at org.eclipse.papyrus.uml.diagram.composite.custom.utils.CompositeStructureDiagramUtils.getInitialPortLocation(CompositeStructureDiagramUtils.java:158)
	at org.eclipse.papyrus.uml.diagram.composite.custom.edit.policies.CompositeSideAffixedNodesCreationEditPolicy$1.figureMoved(CompositeSideAffixedNodesCreationEditPolicy.java:61)
	at org.eclipse.draw2d.Figure.fireFigureMoved(Figure.java:496)

org.eclipse.core.runtime.AssertionFailedException: null argument:location cannot be null
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.gmf.runtime.diagram.ui.commands.SetBoundsCommand.<init>(SetBoundsCommand.java:72)
	at org.eclipse.papyrus.uml.diagram.composite.custom.edit.policies.CompositeSideAffixedNodesCreationEditPolicy$1.figureMoved(CompositeSideAffixedNodesCreationEditPolicy.java:62)
	at org.eclipse.draw2d.Figure.fireFigureMoved(Figure.java:496)

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
@J17359 Let me know if I can work on this. I investigated a bit before and it is a bug in Papyrus so I need to override the default papyrus behaviour. I would assume that it would take 1 - 2 days. Otherwise, please let me know which one to work on next.

**Comment by J17359** [comment]
@ysroh yes, please work this ticket next. Then #63, then #74. I'll mark all three "NGC Approved". I meet with my program tomorrow to discuss our top priorities from our user findings so that list may change but I'll update you via email if it does. Thanks!

**Comment by ysroh** [comment]
@J17359  Thanks

**Comment by ysroh** [comment]
Closing

**Comment by j26151** [comment]
This looks fixed on my end. Thank you.
