### ISSUE TITLE
DDK ZdlGen editor does not work with ZMLMM and CCM domain

### ISSUE THREAD

**Issue by ysroh** [ZeligsoftDev/CX4CBDDS#349]
# **Issue and tracking information**

While I was working on a bug fix I discovered the following issues with DDK.

1. Unable to reload ZMLMM.zdlgen. Open ZMLMM.zdlgen and perform reload on ZMLMM.uml. This throws an exception.
    This prevents us from updating the metamodel in ZMLMM.
![image](https://user-images.githubusercontent.com/896503/143085417-0e870607-c18a-43f6-aa91-f963b679f701.png)

2. UML meta-attribute mapping not showing up on ZMLMM.zdlgen and CCM.zdlgen
![image](https://user-images.githubusercontent.com/896503/143085048-6a0df77b-b9e7-49df-af4c-32d0200cbeba.png)

3. Custom code in zdlgen.editor throws exceptions.
!STACK 0
java.lang.NullPointerException
	at com.zeligsoft.ddk.zdl.zdlgen.provider.GenDomainReferenceItemProvider.getText(GenDomainReferenceItemProvider.java:131)
	at org.eclipse.emf.edit.provider.AdapterFactoryItemDelegator.getText(AdapterFactoryItemDelegator.java:84)
	at com.zeligsoft.ddk.zdl.zdlgen.presentation.ZDLGenEditor.setStatusLineManager(ZDLGenEditor.java:1517)
	at com.zeligsoft.ddk.zdl.zdlgen.presentation.ZDLGenEditor.setSelection(ZDLGenEditor.java:1496)
	at com.zeligsoft.ddk.zdl.zdlgen.presentation.ZDLGenEditor$6.selectionChanged(ZDLGenEditor.java:860)

This needs to be further investigated.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
Fixed this issue by reverting the ZDLGen ecore model and manually adding the required field to generate source code.
